### ISSUE TITLE
android:layout_height is no effect

### ISSUE THREAD

**Issue by scrat000** [Leaking/SlideSwitch#2]
SlideSwitch could not use android:layout_height control it's height

**Comment by Leaking** [comment]
You can use android:layout_height control its height .

if you use circle shape,,your width must larger than height. otherwise the width wiil be automatically set twice of height.

Anyway, the layout_height always  works, but sometimes the layout_width not works (if you use circle shape and the width is litter than height)

``` java
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        int width = measureDimension(280, widthMeasureSpec);
        int height = measureDimension(140, heightMeasureSpec);
        if (shape == SHAPE_CIRCLE) {
            if (width < height)
                width = height * 2;
        }
        setMeasuredDimension(width, height);
        initDrawingVal();
    }
```

**Comment by scrat000** [comment]
thanks
